### ISSUE TITLE
đặc tả bằng bảng

### ISSUE THREAD

**Issue by doanwebute** [doanwebute/BusMapApp#5]

**Comment by nhhao** [comment]
https://github.com/doanwebute/BusMapApp/blob/main/DacTaYeuCauSuDungBang.md

### Busmap - Đặc tả yêu cầu bằng bảng

| Condition                                | Action                                                                                      |
| ---------------------------------------- | ------------------------------------------------------------------------------------------- |
| Nhận thông tin về địa điểm từ khách hàng | Trả về các tuyến xe phù hợp                                                                 |
| Nhận yêu cầu lịch sử di chuyển gần đây   | Trả về thông tin các tuyến xe và địa điểm đã đi gần đây                                     |
| Đọc ký tự được nhập vào từ khách hàng    | Trả về các kết quả điểm đến khớp với những gì khách hàng đang nhập vào (cập nhật real-time) |
